name: Hidden-Face 2024: 히든페이스 보기, 다시 보기, 누누 티비 & 토렌트 - KOREAN 영화 무료 보기

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom action
        uses: ./my-action
        with:
          name: 'GitHub Actions'
