name: My Custom Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom action
        uses: ./my-action
        with:
          name: 'GitHub Actions'
